### PR TITLE
Added motor support and images + Example code

### PR DESCRIPTION
**Pull request by gregcavaretta**
Idea is to have the motors be animated and have sound in the future. 

alt text

Made changes to:
- tkgpio.py
  * Added Class TkMotor()
  * Updated default_setup dictionary
  * Reformatted to Intellij coding convention (I couldn't help this, Pycharm just does this)
  
- motor_example.py
  * Added example for setting up a motor
 
- .gitignore
  * .idea/.DS_Store (Its an OSx thing)

### CODE REVIEW

**Comment by wallysalami** [comment]
Hello, there!

First of all, thanks for the pull request! A DC Motor component is a nice addition, since it is cool and not that hard to implement using the existing code base.

The good things in your code so far:

  - You have put a good code example in `docs` folder.
  - You have update the default_setup. 
  - Docstring for public methods is a good ideia. I'll try some text structures first and then add more of these in the future.
  - As a macOS user, I agree that `.DS_Store` should be in `.gitignore`. In fact, it should be ignored in all folders.

Things to improve and consider before the merge:

  - Sound effects are not necessary for this component.
  - Instead of using a list for the pins, I think they should have separate parameters (forward_pin and backward_pin), just like TkDistanceSensor and [gpiozero's Motor class](https://gpiozero.readthedocs.io/en/stable/api_output.html#motor).
  - So far I am not making any parameter validation. This should be carefully considered before implemented: what types of verifications to make, where exactly to write them (there is a base class, after all), how to write the error messages, etc. Hence I would remove this part for now.
  - Animation is super important here, because DC motors can spin with different speeds in both directions. I was thinking about a front angle with some spinning indicators, like Proteus does (but prettier). We could have a background image and rotate a second image in `update`, changing the angle according to the speed.

DC Motor spinning in Proteus .

Currently I am a little busy with my classes. If you wish to implement or just start these changes, go ahead!

**Comment by gregcavaretta** [comment]
Hello,

I was in the process of writing code to animate the motor based on speed from the pin state (float 0-1). It would just flash between the off and rotate state, having a background and foreground image is definitely a better way to go. I agree that there should be animation. I just didn't include it in this commit, as I was having a problem updating the pictures because it would lag the application. I will probably use multi-threading for that. 

Brief background:
I just graduated from college a couple months ago and I actually saw a news article about this project and brought it up to my robotics professor. One of the things we worked on in Robotics, was building a car/robot that could navigate a maze without getting stuck. I told my professor that I would build him homework assignments using this project. 

So in my case I would be using the motor as wheels, so I'll add multiple types of motors that look different. I want to be able to design an example that looks [similar to the robot we made](https://www.adafruit.com/product/3216). Which brings me to another thought I had. I was thinking about adding another parameter for image rotation so there wouldn't be the need to add the same motor pictures 4 times. This is not necessary but would be nice.

I know some graphic design people that could definitely help with animation of motors/design. I don't know if you're using the images from [Fritzing](https://github.com/fritzing/fritzing-parts/blob/develop/svg/core/breadboard/dc_motor_leg.svg) but I can have new motors designed. 


```
#The formula used
def flashMotor(self, isForward, speed):
        """
        This function waits for 0.1 / x
        :param isForward: True or False, displays a certain picture
        :param speed: Speed is pin.state -  Higher number = faster flashes
        :return: Nothing
        """
        if (0.1 / speed) > 1:
            sleep(1)
        else:
            sleep(0.1 / speed)

        self._change_widget_image("off")
```

I will change this, but the basic idea is to use the `pin.state` value to set the speed of the animation.


Things I will change:
- Shelf the sound idea.
- Change the parameters for the `TkMotor` class to include those parameters. 
- I will remove the pin validation on `line 489`. Because I was using a list I tried to take into account the fact that someone might not pass a list and just an `int`, but your comment on using parameters instead is a better idea. 

My thoughts on the validation issue(s):
- I think that there needs to be validation. One of these types of validation is to make sure that the pin is available, I made the mistake yesterday using GPIO pin 20, Which is obviously a ground pin and my motor code wouldn't work at all. My suggestion would be to implement a pinout map for the Raspberry pi (JSON or some serialized object like a dictionary). In addition to this, have an operations mode in the base class that could be changed for other devices like Arduino or Raspberry pi hats that offer extra GPIO pins (If someone down the road wanted to pull/push that code). 
- If an invalid pin was used I would throw something along the lines of `raise Exception("INVALID GPIO PIN: Pin {PIN_X} is {Dict[PIN_X]["pin_description"]}")`.  Maybe `MockFactory` already does this, I don't know. 
- Things like validation for whether or not GPIO pin(s) are set to a HIGH/LOW state would border on tedious, as complex hardware like a LiDar, Daisychained Pis, etc are in constantly changing states. 
- Validation for whether or not a pin is already in use would be helpful. I'm thinking a `print()` warning message is suitable for this. 
- I think the base class should handle the bulk of verification.

I will start work on these changes, I want to make sure you are okay with my thought process first though.

**Comment by wallysalami** [comment]
> I just graduated from college a couple months ago and I actually saw a news article about this project and brought it up to my robotics professor. One of the things we worked on in Robotics, was building a car/robot that could navigate a maze without getting stuck. I told my professor that I would build him homework assignments using this project.

Cool! I'm very glad my humble library is being useful for other people. By the way, is [this](https://www.tomshardware.com/news/raspberry-pi-gpio-emulator-simulates-physical-components) the news article you saw? 

> I know some graphic design people that could definitely help with animation of motors/design. I don't know if you're using the images from Fritzing but I can have new motors designed.

Thanks for the suggestion, but I'm drawing the images myself. That way I can keep the style consistent and avoid copyright issues. But I definitely get some inspiration from Fritzing. You can use placeholder images for now, and I will update them after the merge.

> I just didn't include it in this commit, as I was having a problem updating the pictures because it would lag the application. I will probably use multi-threading for that.

All UI code must run on the main thread, actually. And don't underestimate the power of pillow + tkinter. TkLCD can render a new image (with the rectangles and characters) many times per second without impacting the performance.

Also this code

```Python
        if (0.1 / speed) > 1:
            sleep(1)
        else:
            sleep(0.1 / speed)
```

would freeze the UI, which would be a bad idea. That is why I use tkinter's loop and run the user's `main` function on a thread – check TkCircuit's `run` method. My `_update_outputs` calls all components every 10ms, and they refresh only if necessary.

> EDIT: Having a base motor (Background) and multiple attachments for the motor (like a wheel or fan picture) is a much better route.

I think using a discrete set of rotation states would not be good for slow speeds. We should just have a base fan/wheel image and rotate it according to an instance variable for the current angle. [This StackOverflow example](https://stackoverflow.com/a/15736974/2286617) uses TKCanvas + pillow, and it works great. We can combine that with a code like TkLED's `update`, which changes the image saturation according to the PWM value.

> I was thinking about adding another parameter for image rotation so there wouldn't be the need to add the same motor pictures 4 times.

Exactly. We can load+cache 1 fan/wheel image and use pillow/canvas to render it, just like TkLED.

> EDIT: I have since checked and done error testing of my own and I can say that MockFactory does a very good job of validation of pins. I am still trying to get familiar with your code.

MockFactory is the magic behind tkgpio, allowing me to easily hijack gpiozero's APIs and map it to tkinter. But I didn't dive deep enough to check their validation logic. Anyway, let's leave that for another time and focus on new components / features for now.

**Comment by wallysalami** [comment]
I've implemented the motor component myself, using the same idea from StackOverflow. Check the `analog_control.py` example.

**Pull request closed without merging**
